name: '6_best_model_refining'

method: 'grid'

metric:
  goal: 'maximize'
  name: 'val_accuracy'

parameters:
  experiment_name:
    value: '6_best_model_refining'
  MODEL:
    value: 'best_model_sweep'
  DATASET_DIR:
    value: '/ghome/group07/M3-Project-new/Week4/MIT_small_train_1'
  VALIDATION_SAMPLES:
    value: 807
  CALLBACKS:
    value: False
  IMG_WIDTH:
    value: 64
  IMG_HEIGHT:
    value: 64
  BATCH_SIZE:
    values: [8, 16,32,64]
  EPOCHS:
    value: 300
  LEARNING_RATE:
    value: 0.001
  MOMENTUM:
    value: 0.9
  WEIGHT_DECAY:
    value: 0.0001
  OPTIMIZER:
    value: 'adam'
  LOSS:
    value: 'categorical_crossentropy'

  num_blocks:
    value: 4
  second_layer:
    value: True
  third_layer:
    values: [True, False]
  num_denses:
    value: 3      # Canvia aqui respecte la baseline
  dim_dense:
    value: 256    
  filters1:
    value: 32
  filters2:
    value: 64
  batch_norm: 
    value: True
  dropout:
    value: True
  dropout_range:
    values: [[0.6, 0.5, 0.3],[0.7,0.6,0.4], [0.8,0.7,0.5]]
  kernel_size:
    value: 3
  kernel_regularizer:
    values: True
  strides:  
    value: 1
  initializer:
    value: 'glorot_normal'
  non_linearities:
    value: 'mish'
  pool_size:
    value: 2


  hardcore_data_augmentation:
    value: False
  horizontal_flip:
    value: True
  vertical_flip:
    value: False
  rotation:
    value: 0
  width_shift:
    value: 0.1
  height_shift:
    value: 0.1
  shear_range:
    value: 0
  zoom_range:
    value: 0
  brightness_range:
    value: [0.5, 1.5]

