wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1674074147.703399
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
      10:
      - 9
hyper:
  desc: null
  value: parameter
