name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        # flake8-bugbear flake8-comprehensions are useful but not available internally
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==6.0.0 isort==5.11.4
          python -m pip install black[jupyter]
          flake8 --version
      - name: Lint
        run: |
          echo "Running isort"
          isort -c .
          echo "Running black"
          black -l 100 --check .
          echo "Running flake8"
          flake8 --max-line-length 100 .
